name: Build ZMK
run-name: ${{ github.event_name }} by ${{ github.actor }}
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
jobs:
  Build-ZMK:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/zephyrproject-rtos/ci:v0.26.11
      options: "--entrypoint /bin/bash"

    steps:
      - name: set_env
        run: |
          if [ "${{ github.event_name }}" = "pull_request" -o "${{ github.event_name }}" = "pull_request_target" ];then
            echo "This is pull request"
            echo "ZMK_REPOSITORY=${{ github.repository }}" >> $GITHUB_ENV
            echo "ZMK_REF=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          fi

          if [ "${{ github.event_name }}" = "push" ];then
            echo "This is push"
            echo "ZMK_REPOSITORY=${{ github.repository }}" >> $GITHUB_ENV
            echo "ZMK_REF=${{ github.ref }}" >> $GITHUB_ENV
          fi

      - name: print_env
        run: |
          echo "sdk-version -> ${ZSDK_VERSION}"
          echo "zephyr-manifest-repository -> ${ZMK_REPOSITORY}"
          echo "zephyr-manifest-ref: ${ZMK_REF}"

      - name: setup sdk
        shell: bash
        run: |
          echo "zephyr sdk -> zephyr-sdk-${ZSDK_VERSION}"
          ls /opt/toolchains/zephyr-sdk-${ZSDK_VERSION}
          /opt/toolchains/zephyr-sdk-${ZSDK_VERSION}/setup.sh -c

      - name: checkout manifest
        uses: actions/checkout@v4
        with:
          repository: ${{ env.ZMK_REPOSITORY }}
          path: "zmk"
          ref: ${{ env.ZMK_REF }}
          fetch-depth: 0
          persist-credentials: false

      - name: west update
        shell: bash
        run: |
          cd zmk
          west init -l app
          west update

      - name: do build
        shell: bash
        run: |
          cd zmk
          cd app
          west build -p -b rtl8762gn_evb -- -DSHIELD=keychron_q1_ultra_ansi

      - name: upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: keychron_q1_ultra_ansi-firmware
          path: |
            zmk/app/build/zephyr/zmk.uf2
            zmk/app/build/zephyr/zmk.hex
          if-no-files-found: warn

